name: MeowKit
version: 1.0
main: com.meow.meowkit.MeowKit
commands:
  mkit:
    description: MeowKit 插件的主命令
    usage: /mkit <subcommand>
    permission: mkit.admin
    permission-message: 你没有权限执行此命令！
